# Generated by Django 6.0 on 2026-01-12 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='bem',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='bem',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='status',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='endereco',
        ),
        migrations.AddField(
            model_name='bem',
            name='valor_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='codigo',
            field=models.CharField(default='TEMP', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bem',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.sala'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bem',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status'),
        ),
        migrations.AlterField(
            model_name='bem',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidade'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sala',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidade'),
        ),
        migrations.AlterField(
            model_name='status',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='bem',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria'),
        ),
    ]
